import { motion, useReducedMotion } from 'framer-motion'
import SectionHeading from './SectionHeading'

const EASE = [0.22, 1, 0.36, 1]

const ENTRIES = [
  {
    period: 'Jan 2025 — Present',
    eyebrow: 'Data & BI Analyst · Self-directed',
    title: 'Independent Projects',
    where: 'London, UK',
    // The CV states this plainly; the site should too — an unlabelled portfolio
    // entry sitting in a work timeline reads as a client engagement.
    note: 'Unpaid portfolio work — no client engagement; all code and documentation public on GitHub.',
    points: [
      'Built a bronze/silver/gold PostgreSQL warehouse and star schema over 10,000+ UK Companies House records, replacing record-by-record manual review with a repeatable reporting workflow.',
      'Built the Power BI semantic layer in DAX and Power Query over the gold tables — drill-through watchlist, entity-detail and exception dashboards on scheduled refresh.',
      'Built LLM prompt logic to flag related-party transactions, validated against a hand-verified ground truth sample with reasoning captured for audit.',
      'Built a Retrieval-Augmented Generation (RAG) chatbot delivering source-grounded conversational analytics over business documents.',
      'Built Atlas Analytics, a multi-agent platform where every figure is computed deterministically in Python rather than generated by a language model; validated through 380 automated tests.',
    ],
  },
  {
    period: 'Jan 2024 — Jan 2025',
    eyebrow: 'Education · Birmingham',
    title: 'MSc Business Analytics (Merit) — Aston University',
    where: 'Birmingham, UK',
    points: [
      'Data modelling, predictive analytics, machine learning and data visualisation.',
      'Dissertation applied NLP to financial fraud detection, improving model precision-recall AUC from 0.14 to 0.64.',
    ],
  },
  {
    period: 'Sep — Nov 2024',
    eyebrow: 'BI Intern · Music & media analytics',
    title: 'Koru Green Limited',
    where: 'Remote, UK',
    points: [
      'Built Tableau dashboards over multi-region royalty data, identifying month-on-month revenue trends and supporting commercial performance analysis.',
      'Worked with stakeholders to translate Technical Design Documents (TDDs) into reporting requirements and analytical deliverables.',
      'Cleansed and prepared multi-source earnings data in Python (pandas / Jupyter); managed version control in Git / GitHub.',
    ],
  },
  {
    period: 'Jan 2022 — Dec 2023',
    eyebrow: 'Senior Analyst · IT Service Management',
    title: 'HCLTech — Client: Emirates Global Aluminium (EGA), Dubai',
    where: 'Lucknow, India',
    points: [
      'Delivered SLA and IT Support KPI reporting across 10,000+ tickets annually, consumed by client and internal leadership on weekly and monthly cycles.',
      'Extracted, cleansed and transformed incident data from ServiceNow and BMC Remedy into Excel-based SLA dashboards, giving leadership visibility of breaches, recurring incidents and operational bottlenecks.',
      'Automated recurring reporting, cutting manual report preparation by approximately 20 hours per month.',
      'Reporting supported SLA compliance reaching the mid-90s%, and maintained operational documentation to client standards.',
    ],
  },
  {
    period: 'Sep 2020 — Jan 2022',
    eyebrow: 'Agency Manager · Insurance',
    title: 'HDFC Life',
    where: 'Lucknow, India',
    points: [
      'Analysed branch and regional sales performance in a regulated financial services environment (RBL Bank bancassurance partnership), reporting KPIs to branch and regional stakeholders.',
      'Territory achieved the #1 regional position for premium collection during tenure.',
    ],
  },
  {
    period: '2013 — 2016',
    eyebrow: 'Education · Commerce & Finance',
    title: 'BCom (Honours) — Amity University',
    where: 'India',
    points: [],
  },
]

function Entry({ entry, index }) {
  const reduced = useReducedMotion()
  return (
    <motion.li
      initial={reduced ? false : { opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-60px' }}
      transition={{ duration: 0.7, ease: EASE, delay: 0.05 * index }}
      className="relative grid gap-2 pb-14 pl-8 last:pb-0 md:grid-cols-[180px_1fr] md:gap-10 md:pl-10"
    >
      {/* node marker on the rail */}
      <span
        aria-hidden="true"
        className="absolute top-1.5 left-0 h-2.5 w-2.5 -translate-x-[5px] rotate-45 border border-teal-600 bg-ink-950"
      />
      <p className="font-mono text-[0.72rem] leading-6 tracking-[0.14em] text-slate uppercase">{entry.period}</p>
      <div>
        <p className="eyebrow mb-1.5 text-[0.62rem]">{entry.eyebrow}</p>
        <h3 className="text-lg font-bold tracking-tight text-chalk">{entry.title}</h3>
        <p className="mt-0.5 font-mono text-[0.65rem] tracking-[0.14em] text-slate/80 uppercase">{entry.where}</p>
        {entry.note && (
          <p className="mt-3 border-l-2 border-amber-600/50 py-0.5 pl-3 text-[0.82rem] leading-relaxed text-slate/90 italic">
            {entry.note}
          </p>
        )}
        {entry.points.length > 0 && (
          <ul className="mt-3 flex flex-col gap-2">
            {entry.points.map((pt) => (
              <li key={pt} className="flex gap-3 text-[0.92rem] leading-relaxed text-slate">
                <span aria-hidden="true" className="mt-[0.55em] h-px w-4 shrink-0 bg-teal-600/70" />
                {pt}
              </li>
            ))}
          </ul>
        )}
      </div>
    </motion.li>
  )
}

export default function Experience() {
  return (
    <section id="experience" className="mx-auto max-w-[1200px] px-6 py-24 md:px-10 md:py-28">
      <SectionHeading number="04" eyebrow="Experience">
        Where the discipline came from.
      </SectionHeading>
      <ol className="relative border-l border-line/60">
        {ENTRIES.map((e, i) => (
          <Entry key={e.title} entry={e} index={i} />
        ))}
      </ol>
    </section>
  )
}
